### ISSUE TITLE
Ignore entries from other `known_` sections?

### ISSUE THREAD

**Issue by beniwohli** [asottile/seed-isort-config#10]
For a Django project, I like to have all the `django` imports in its own section. I do this using isort's custom sections:

    known_django=django

As it is, seed-isort-config ignores this setting, adding `django` to `known_third_party`, which takes precedence in isort.

I think it would make sense to ignore modules from any other `known_` section when assembling the `known_third_party` list.

**Comment by asottile** [comment]
If you want this, please send a tested pr :)

seed-isort-config currently does _no_ reading of configs so this might be difficult

Also seems like a bit of an odd use case to me, Django would already sort together why bother with a nonstandard separate section?
