### ISSUE TITLE
Prevent library from being added by hook

### ISSUE THREAD

**Issue by jambonrose** [asottile/seed-isort-config#15]
Thanks for the package, I'm finding it really useful.

I'm currently trying to use this when building a library, `django-verified-user`, which defines the `verified_user` namespace.

When I run `seed-isort-config` from the command line, it detects that the library has been installed using `./setup develop` and prevents `verified_user` from being added to the list of `known_third_party`.

However, using `seed-isort-config` as a `pre-commit` hook runs the tool in a separate virtual environment, meaning it doesn't detect the local installation and adds `verified_user` to `known_third_party`.

I'd like some way to prevent `seed-isort-config` from adding `verified_user` to `known_third_party` when it's run as a hook.

One possible solution is similar to #10: detect that `verified_user` is specified in `known_first_party` to ensure it's never added to `known_third_party`.

Another would be to add an `exclude-pkg` (`excludepkg`? `exclude-dep`?) flag to the command, allowing me to simply specify `args: [--exclude-pkg=verified_user,not_included_either]` in `.pre-commit-config.yaml`

Happy to put together a PR if one of these sounds more desirable than the other. I'm leaning towards the second option due to implementation simplicity, but defer to you, @asottile.

**Comment by asottile** [comment]
Can you show me your repository layout? I suspect you're using a `./src` layout and need to use `--aplication-directories`?

**Comment by asottile** [comment]
Then you'll want:

```yaml
    vars: [--application-directories=src]
```

(or `--application-directories=.:src` if you also have top level things like your tests)

**Comment by asottile** [comment]
For example: https://github.com/tox-dev/tox/blob/6259ff17f285563d2a31c0eb90a782eb82c17fac/.pre-commit-config.yaml#L14-L18

**Comment by jambonrose** [comment]
Aha! I thought I'd tried that, but clearly hadn't gotten it right. Thank you very much.

I'm using `args: [--application-directories, 'src:.']`, as the colon outside of a string causes YAML issues.

**Comment by asottile** [comment]
sweet, might be worth updating the docs -- want to suggest an edit to the README? seems [reorder_python_imports](https://github.com/asottile/reorder_python_imports) has a callout for the option but not this :man_shrugging:

**Comment by jambonrose** [comment]
I was just planning to! I'd like to update the docs with examples for this, as well as exclude, if that sounds alright by you.

**Comment by asottile** [comment]
Sounds good -- thanks!
