### ISSUE TITLE
check mode

### ISSUE THREAD

**Issue by gaborbernat** [asottile/seed-isort-config#21]
Can we create a check mode, to fail in CI if this makes changes (when using it outside of pre-commit)?

**Comment by asottile** [comment]
It's not really designed to work outside of pre-commit, though I believe it already exits nonzero when making changes

**Comment by asottile** [comment]
(that said, it probably works fine outside!)

**Comment by gaborbernat** [comment]
Works for me, other than returning non-zero when making changes. 🤔

**Comment by asottile** [comment]
Oh indeed, woops I was thinking of another repo, that should probably happen here too
