### ISSUE TITLE
print changes on stdout

### ISSUE THREAD

**Issue by gaborbernat** [asottile/seed-isort-config#25]
I run this now part of the tox steps (seed --check, black --check, isort --check). Currently when this command fails leaves you wondering what would actually change, can we print to the standard output the changes to the list (maybe via some verbose mode or by default)?

**Comment by asottile** [comment]
hmm yeah it seems to write out things [if the setting didn't exist](https://github.com/asottile/seed-isort-config/blob/4d8d9e7fddad11a9ccc757fce38bd36a39538c84/seed_isort_config.py#L120-L124), but not if the setting exists.  patches welcome!
