### ISSUE TITLE
FileNotFoundError thrown after tweaking directory structure

### ISSUE THREAD

**Issue by jadchaar** [asottile/seed-isort-config#37]
I am getting the following error suddenly after making a few tweaks to my directory structure:
```
hookid: seed-isort-config

Traceback (most recent call last):
  File "/Users/jadchaar/.cache/pre-commit/repojmc2zze7/py_env-python3/bin/seed-isort-config", line 10, in <module>
    sys.exit(main())
  File "/Users/jadchaar/.cache/pre-commit/repojmc2zze7/py_env-python3/lib/python3.7/site-packages/seed_isort_config.py", line 101, in main
    third_party = third_party_imports(filenames, appdirs)
  File "/Users/jadchaar/.cache/pre-commit/repojmc2zze7/py_env-python3/lib/python3.7/site-packages/seed_isort_config.py", line 51, in third_party_imports
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tests/helpers/utils.py'
```

Here is the source code that is causing the issue: https://github.com/jadchaar/sec-edgar-downloader/tree/ab45fad4a6aaddb9df33d02d5a0e4a03469b4a2b.

Here are the steps I take before getting the error:
1. Move `utils.py` out of the `helpers` folder of my testing directory
2. Delete the `helpers` directory
3. Remove the line `sys.path.append(str(Path(__file__).parent.joinpath("helpers")))` from the `conftest.py`
4. Change the import to `from .utils import strip_cik, verify_directory_structure` in `test_filing_downloads.py`

It definitely has something to do with removing `sys.path.append(str(Path(__file__).parent.joinpath("helpers")))`, but I have no idea how to fix this.

I tried deleting the `pre-commit` cache, but that did not help :(.

**Comment by asottile** [comment]
seems a bug in `seed-isort-config`, it's unrelated to your code:

```console
$ rm t.py
$ git status
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    t.py

no changes added to commit (use "git add" and/or "git commit -a")
$ pre-commit  try-repo https://github.com/asottile/seed-isort-config --all-files
[INFO] Initializing environment for https://github.com/asottile/seed-isort-config.
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: 8d7307853a277f9f5e55a2ae66d8e413fd99bbf7
    hooks:
    -   id: seed-isort-config
===============================================================================
[INFO] Installing environment for https://github.com/asottile/seed-isort-config.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
seed isort known_third_party.............................................Failed
hookid: seed-isort-config

Traceback (most recent call last):
  File "/tmp/tmpzdz5smsr/repo1_z9sy2r/py_env-python3/bin/seed-isort-config", line 10, in <module>
    sys.exit(main())
  File "/tmp/tmpzdz5smsr/repo1_z9sy2r/py_env-python3/lib/python3.6/site-packages/seed_isort_config.py", line 101, in main
    third_party = third_party_imports(filenames, appdirs)
  File "/tmp/tmpzdz5smsr/repo1_z9sy2r/py_env-python3/lib/python3.6/site-packages/seed_isort_config.py", line 51, in third_party_imports
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 't.py'

```

Should be pretty easy if you'd like to make a contribution -- just needs an existence check before trying to parse each file (since it's possible that `git ls-files` tells us about files that were deleted)

**Comment by jadchaar** [comment]
I can take a whack at it when I get a chance this week :).

**Comment by asottile** [comment]
should be a one line patch here: https://github.com/asottile/seed-isort-config/blob/8d7307853a277f9f5e55a2ae66d8e413fd99bbf7/seed_isort_config.py#L50

plus a small test here: https://github.com/asottile/seed-isort-config/blob/master/tests/seed_isort_config_test.py (basically just need to emulate a test which `git add`s a file and then deletes it (without using `git rm`)

**Comment by jadchaar** [comment]
@asottile does this occur only after doing `git add`? I don't remember doing a `git add` call before this occurred :(. I am wondering if it simply the act of removing a file or folder.
