### ISSUE TITLE
does it identify absolute imports?

### ISSUE THREAD

**Issue by lokesh1729** [asottile/seed-isort-config#39]
hey,

one quick question if i have code like this

```
import os
import sys

from rest_framework import status
from faker import Faker

from django.contrib.auth import authenticate
from django.http.response import HttpResponse

from . import utils
from . import constants
from data_controller import constants as dc_constants
from data_aggregator import utils as da_utils
```

will it consider `data_controller` and `data_aggregator` as third-party packages ?? because I cannot use relative imports like `..data_controller import constants as dc_constants` in my django project as it is throwing `ValueError: attempted relative import beyond top-level package` for some reason, also it's not a good practice according to two scoops of django.

**Comment by asottile** [comment]
Sounds to me like you're using `python path/to/file.py` when you should be using [`python -m path.to.file`](https://github.com/asottile/scratch/wiki/PythonPathSadness)

`seed-isort-config` uses python3.x import semantics -- if you have an implicit relative import it'll treat that as a third party import
