### ISSUE TITLE
endless add/remove cycle for `known_third_party` under certain conditions

### ISSUE THREAD

**Issue by jmknoble** [asottile/seed-isort-config#40]
**seed-isort-config** seems to undergo an endless cycle of adding/removing modules to `known_third_party` under certain conditions:

1. There is more than one third-party module used in the Python source files visited by **seed-isort-config**.
2. There is exactly one of those third-party modules listed in the value for the `known_third_party` key in **.isort.cfg**.
3. A `known_first_party` key exists in **.isort.cfg** with no value.

This appears to be due to a greedy whitespace pattern in `KNOWN_OTHER_RE` which matches newlines and gloms `known_third_party` onto the value for `known_first_party`.

A full explanation and steps to reproduce are in https://github.com/jmknoble/testcase-seed-isort-config .

An apparent quick fix is in https://github.com/jmknoble/seed-isort-config .  Caveats:  I'm unsure whether this was intended to match patterns like:

```ini
known_first_party = a_module,
        another_module,
        yet_another_module
```

which is valid, but much harder to match with regexes.

I'm guessing the reason **seed-isort-config** is using regexes is because of the lack of fidelity in reading/writing CFG/INI files in the builtin ConfigParser.  Ideally, **seed-isort-config** should probably avoid the pitfalls of regexes and use something like [configupdater](https://pypi.org/project/configupdater/) or [ConfigObj](https://github.com/DiffSK/configobj) for CFG/INI files and [tomlkit](https://pypi.org/project/tomlkit/) for TOML files, but I understand reasons like "should support Python 2.7 while it's still alive" and "part of the reason for TOML is that CFG/INI file formats are all so subtly different".

So I'd rather see the whitespace be less greedy and expect `known_*` values to be all on one line rather than create other, possibly more subtle and less solvable, problems.

**Comment by asottile** [comment]
yeah this is not supported, put it all on one line

**Comment by jmknoble** [comment]
Whoa, you close too fast.

The issue is not whether something should be all on one line.  I'm fine with it being all on one line.  The issue is the flapping back and forth with an empty `known_first_party`.

Happy to submit a pull request with the fix, or you can take the time to read the reproduction.

**Comment by asottile** [comment]
my bad, I thought this was about multi line matches which are intentionally not supported -- if it's something else please make a tested PR :+1:

**Comment by asottile** [comment]
I suspect this is a better patch, though I'm not sure I completely understand the issue and/or if it fixes it:

```diff
-THIRD_PARTY_RE = re.compile(r'^known_third_party(\s*)=(\s*?)(?:\S.*)?$', re.M)
-KNOWN_OTHER_RE = re.compile(
-    r'^known_((?!third_party)\w+)\s*=\s*(.*)$', re.M,
-)
+THIRD_PARTY_RE = re.compile(r'^known_third_party( *)=( *)(?:.*)?$', re.M)
+KNOWN_OTHER_RE = re.compile(r'^known_((?!third_party)\w+) *= *(.*)$', re.M)
```

**Comment by jmknoble** [comment]
That approach may be clearer, since non-greedy patterns are not as longstanding a feature in regexes and therefore likely not quite as obvious.  At the very least, though, I would add support for tab characters, like so:

```diff
-THIRD_PARTY_RE = re.compile(r'^known_third_party(\s*)=(\s*?)(?:\S.*)?$', re.M)
-KNOWN_OTHER_RE = re.compile(
-    r'^known_((?!third_party)\w+)\s*=\s*(.*)$', re.M,
-)
+THIRD_PARTY_RE = re.compile(r'^known_third_party([ \t]*)=([ \t]*)(?:.*)?$', re.M)
+KNOWN_OTHER_RE = re.compile(r'^known_((?!third_party)\w+)[ \t]*=[ \t]*(.*)$', re.M)
```

Once I get a pipeline stood up in Azure DevOps to build the existing fork I'll try out the above to validate it.

**Comment by jmknoble** [comment]
The above (with `[ \t]*`) works correctly against the testcase.

```diff
✔ ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [master|✔] 
20:48 $ git checkout -f without-greedy-whitespace
Note: checking out 'without-greedy-whitespace'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c18169d Use forked seed-isort-config without greedy whitespace in regex
✔ ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [without-greedy-whitespace|✔] 
20:48 $ gvim .pre-commit-config.yaml 
✔ ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [without-greedy-whitespace|✔] 
20:48 $ git diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 16a5e3d..e457a24 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -7,7 +7,7 @@ default_language_version:
 
 repos:
   - repo: https://github.com/jmknoble/seed-isort-config
-    rev: v1.9.2
+    rev: 917687899374cb007f8de1308c56c6e753d643b4
     hooks:
       - id: seed-isort-config
         args: ['--exclude=(docs?|examples?|tests?|utils?)/.*\.py']
✔ ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [without-greedy-whitespace|✚ 1] 
20:49 $ pre-commit run --all-files
seed isort known_third_party.............................................Failed
hookid: seed-isort-config

Files were modified by this hook.

✘-1 ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [without-greedy-whitespace|✚ 2] 
20:49 $ git diff .isort.cfg
diff --git a/.isort.cfg b/.isort.cfg
index cf6a930..0cf7afe 100644
--- a/.isort.cfg
+++ b/.isort.cfg
@@ -4,4 +4,4 @@
 
 known_first_party =
 
-known_third_party =dummy_thirdparty1
+known_third_party =dummy_thirdparty1,dummy_thirdparty2
✔ ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [without-greedy-whitespace|✚ 2] 
20:49 $ pre-commit run --all-files
seed isort known_third_party.............................................Passed
✔ ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [without-greedy-whitespace|✚ 2] 
20:49 $ git diff .isort.cfg
diff --git a/.isort.cfg b/.isort.cfg
index cf6a930..0cf7afe 100644
--- a/.isort.cfg
+++ b/.isort.cfg
@@ -4,4 +4,4 @@
 
 known_first_party =
 
-known_third_party =dummy_thirdparty1
+known_third_party =dummy_thirdparty1,dummy_thirdparty2
✔ ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [without-greedy-whitespace|✚ 2] 
20:49 $ 
```

**Comment by jmknoble** [comment]
This may illustrate the issue better:

```
✔ ~/Stuff/RevisionControl/github.com/jmknoble/testcase-seed-isort-config [with-2-third-party-modules|✚ 1] 
21:12 $ ~/.cache/pre-commit/repom5b3r75y/py_env-python3/bin/python -m pdb ~/.cache/pre-commit/repom5b3r75y/py_env-python3/bin/seed-isort-config 
> /Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/bin/seed-isort-config(3)<module>()
-> import re
(Pdb) run '--exclude=(docs?|examples?|tests?|utils?)/.*\.py'
Restarting /Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/bin/seed-isort-config with arguments:
	/Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/bin/seed-isort-config
> /Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/bin/seed-isort-config(3)<module>()
-> import re
(Pdb) break 10
Breakpoint 1 at /Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/bin/seed-isort-config:10
(Pdb) c
> /Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/bin/seed-isort-config(10)<module>()
-> sys.exit(main())
(Pdb) step
--Call--
> /Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/lib/python3.7/site-packages/seed_isort_config.py(74)main()
-> def main(argv=None):
(Pdb) break 121
Breakpoint 2 at /Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/lib/python3.7/site-packages/seed_isort_config.py:121
(Pdb) c
> /Users/u0126571/.cache/pre-commit/repom5b3r75y/py_env-python3/lib/python3.7/site-packages/seed_isort_config.py(121)main()
-> third_party -= set(load(match.group(2)))
(Pdb) p filename
'./.isort.cfg'
(Pdb) p match.group(2)
'known_third_party =dummy_thirdparty1,dummy_thirdparty2'
(Pdb) p load(match.group(2))
['known_third_party =dummy_thirdparty1', 'dummy_thirdparty2']
(Pdb) p set(load(match.group(2)))
{'known_third_party =dummy_thirdparty1', 'dummy_thirdparty2'}
(Pdb) p third_party
{'dummy_thirdparty2', 'dummy_thirdparty1'}
(Pdb) p third_party - set(load(match.group(2)))
{'dummy_thirdparty1'}
(Pdb) 
```

The above is the second time through (seed-isort-config correctly added the 2nd module to `known_third_party` on the first run).

The greedy regex in `KNOWN_OTHER_RE` is capturing the entire `known_third_party` line as `match.group(2)`.  Splitting that at the comma and turning it into a set means the second item on that line gets removed from `third_party`.  When we finally process the THIRD_PARTY_RE, the 2nd module has now been removed from the set, which then replaces what was there.
