### ISSUE TITLE
Add support for setup.cfg

### ISSUE THREAD

**Issue by rmorshea** [asottile/seed-isort-config#49]
It would be great if we could seed into `setup.cfg` instead of `.isort.cfg` if the latter doesn't exist.

**Comment by asottile** [comment]
it.... already does?

```console
$ tail -2 setup.cfg 
[isort]
known_third_party=
$ seed-isort-config 
$ tail -2 setup.cfg 
[isort]
known_third_party=aspy,mock,pytest,setuptools
```

**Comment by rmorshea** [comment]
Oh, the docs on `isort` now say to use `tools:isort` instead of `isort`.

**Comment by rmorshea** [comment]
Sorry, `[tool:isort]` is an alternative to `[isort]` section name.

**Comment by asottile** [comment]
yes

```

```console
$ tail -2 setup.cfg 
[tool:isort]
known_third_party=
$ seed-isort-config 
$ tail -2 setup.cfg 
[tool:isort]
known_third_party=aspy,mock,pytest,setuptools
```

**Comment by rmorshea** [comment]
My apologies, I didn't realize I needed to have the empty `known_third_party=` there. Maybe a useful thing to add to the README. Thanks for your help!

**Comment by rmorshea** [comment]
My god I'm terrible at reading...

**Comment by asottile** [comment]
🤣

**Comment by rmorshea** [comment]
Thanks for dealing with me. It's been a long day.

**Comment by asottile** [comment]
<3 it's been a long day for you and me both friendo

**Comment by Vivalldi** [comment]
It should also be noted that those of you coming to this, you need `setup.cfg`  staged in git with the `known_third_party=` (or previously committed). I kept trying to get this to work but the `isort.cfg` was constantly being generated. Staging `setup.cfg` did the trick

**Comment by asottile** [comment]
`seed-isort-config` doesn't care if it's staged or not for rewriting -- probably you were missing the blank setting which it does care about

**Comment by Vivalldi** [comment]
Maybe? I had the blank setting in the file but was running `seed-isort-config` through `pre-commit` with `pre-commit run seed-isort-config`. I imagine that it's an issue only when running through `pre-commit`.

I'll install `seed-isort-config` independently and test. My inclination is that you're correct

**Comment by asottile** [comment]
it's really not I promise <3 I'm the author of both tools and pre-commit literally just calls `seed-isort-config`, nothing special

**Comment by Vivalldi** [comment]
So I just verified it locally. Here's a minimum reproducible repo https://github.com/Vivalldi/seeder-issue

Steps to reproduce in that repo (once cloned)

1. Add `known_third_party=` to `[isort]` in `setup.cfg` and save.
Do not stage file

2. Run `seed-isort-config`
Verify that `pandas` is now in `known_third_party=`

3. Reset `setup.cfg` to have `known_third_party=`
Do not stage file

4. Run `pre-commit run seed-isort-config`
`.isort.cfg` is generated & `setup.cfg` is not updated

**Comment by asottile** [comment]
works for me?

```diff
$ git diff
diff --git a/setup.cfg b/setup.cfg
index 3ec17c2..49385d6 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -4,4 +4,5 @@ multi_line_output = 3
 include_trailing_comma = True
 combine_as_imports = True
 line_length = 88
-force_sort_within_sections = True
\ No newline at end of file
+force_sort_within_sections = True
+known_third_party=
```

```console
$ pre-commit run --all-files
seed isort known_third_party.............................................Failed
- hook id: seed-isort-config
- exit code: 1
- files were modified by this hook
```

```diff
$ git diff
diff --git a/setup.cfg b/setup.cfg
index 3ec17c2..2f41146 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -4,4 +4,5 @@ multi_line_output = 3
 include_trailing_comma = True
 combine_as_imports = True
 line_length = 88
-force_sort_within_sections = True
\ No newline at end of file
+force_sort_within_sections = True
+known_third_party=pandas
```

**Comment by Vivalldi** [comment]
Yeah, it works for me as well if I run `pre-commit run --all-files`. My initial comment was more to let people know they need to stage `setup.cfg` if they are just now putting `known_third_party=` into their `setup.cfg`. 

Here's what I ran

```diff
$ git diff
diff --git a/setup.cfg b/setup.cfg
index 3ec17c2..51d103d 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,4 +1,5 @@
 [isort]
+known_third_party=
 sections = FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
 multi_line_output = 3
 include_trailing_comma = True
```

```
$ pre-commit
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/cosgrove/.cache/pre-commit/patch1586275216.
seed isort known_third_party.............................................Failed
- hook id: seed-isort-config
- exit code: 1

Creating an .isort.cfg with a known_third_party setting. Feel free to move the setting to a different config file in one of .editorconfig, .isort.cfg, setup.cfg, tox.ini, pyproject.toml.

This setting should be committed.

[INFO] Restored changes from /Users/cosgrove/.cache/pre-commit/patch1586275216.
```

```diff
$ git diff
diff --git a/setup.cfg b/setup.cfg
index 3ec17c2..51d103d 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -1,4 +1,5 @@
 [isort]
+known_third_party=
 sections = FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
 multi_line_output = 3
 include_trailing_comma = True
```

I understand it's expected behavior that `pre-commit` stashes unstaged files to run the tools. I just wanted to inform people like me that staging is necessary if you haven't had `known_third_party=` set before.

Apologies for the confusion

**Comment by Vivalldi** [comment]
If you'd like, I'd be more than happy to update the `getting started` section in the `README.md` to mention that the setting should be staged/committed.

**Comment by asottile** [comment]
oh hahaha you ignored the warning:

> [WARNING] Unstaged files detected.
> [INFO] Stashing unstaged files to /Users/cosgrove/.cache/pre-commit/patch1586275216.

no, this shouldn't be added to the README 😆
