### ISSUE TITLE
Incorrectly classifying `dataclasses` as a BUILTIN when it's being installed as a third party

### ISSUE THREAD

**Issue by TMiguelT** [asottile/seed-isort-config#58]
Here's a tricky one. I'm trying to support Python 3.6, so I've included `dataclasses` in my `setup.py` as a dependency. So on my dev machine which is Python 3.6, I run `seed-isort-config`, and it correctly adds `dataclasses` as a third party lib. However on the CI server, under Python 3.7+ `dataclasses` is a built-in library, so `precommit` fails when `seed-isort-config` tries to move `dataclasses` to the built-in section. The correct behaviour here, I believe, is to count it as a third party because it's in the `setup.py` and also installed in the virtualenv under `site_packages`. 

Although my setup is unusual, I think this will happen anytime you try to use a backport library that's already supported on certain Python versions as a built-in.

**Comment by asottile** [comment]
here's previous information on the topic: https://github.com/asottile/reorder_python_imports/issues/85
