### ISSUE TITLE
Not compatible with monorepos

### ISSUE THREAD

**Issue by bbenne10** [asottile/seed-isort-config#62]
Because seed-isort-config uses `git ls-files -- *.py` to find the eligible candidates for walking for third-party dependencies, this lumps all found python files into one category and does not allow for scoping by sub-project in monorepos (those repositories containing multiple sub-projects per git repository).

The support offered by the arguments `settings-path` and `application-directory` help here, but don't fix the problem entirely as we're still walking the all of the files to pick out their third-party deps. This means that for a monorepo with two sub-projects, the output for seed-isort-config will be the same for both. 

For my usecase (and I think this generalizes decently), if I set `application-directories` I would only like seed-isort-config to walk the python files in those directories. Trimming the list of file paths returned by `git ls-file -- *.py` down to those that start with the path I have provided would be a great way to determine a set of files for seed-isort-config to walk. 

I suppose that there's a use case where `application-directories` may not be local (if you're implementing a sub-project outside of the main repository - say for a plugin infrastructure or something). If that's a huge concern, I would think that an additional knob to tweak the path to the code to walk would be appropriate.

I am happy to put in the legwork to make this work right and open a pull request for the changes in question. Just let me know how you'd like me to proceed. Thanks for you time!

**Comment by asottile** [comment]
I believe there's sufficient facilities to already support this without any added complexity, for example

```
.
    project1
         .isort.cfg
         t.py
    project2
        .isort.cfg
        t2.py
```

```bash
seed-isort-config --exclude '^project2/' --settings-path project1 --application-directories project1
seed-isort-config --exclude '^project1/' --settings-path project2 --application-directories project2
```

**Comment by asottile** [comment]
`-exclude '^(?!project1/)'` probably generalizes better than the exclude above

**Comment by bbenne10** [comment]
`-exclude '^(?!project1/)'` is clever and I hadn't considered that. I'll see how that helps.
