### ISSUE TITLE
Different results when run from pre-commit or cli

### ISSUE THREAD

**Issue by wakemaster39** [asottile/seed-isort-config#7]
I am running into an issue where the pre-commit hook is generating a different result when it is run by a pre-commit hook or when it is run from the cli after installing the package. 

When it is run from the CLI it is generating:

```
[settings]
known_third_party=cx_Freeze,py2exe,setuptools,versioneer,werkzeug
```

and the output from the pre-commit is from:

```
[settings]
known_third_party=cx_Freeze,py2exe,setuptools,werkzeug
```

I am unsure where to start with debugging this issue, what additional details or steps do I need to take to provide you with the results that you need?

This causes some issues with isort and it is breaking up third party library versioneer from setuptools in my setup.py file.

**Comment by asottile** [comment]
Do you have a repository I can look at and/or are you passing any commandline arguments?

**Comment by wakemaster39** [comment]
I pulled out part of the project here:

https://github.com/wakemaster39/seed-isort-test

I am not passing any CLI arguments

**Comment by asottile** [comment]
hmmm, ok so my first attempt does not reproduce this:

```bash
rm -rf venv
virtualenv venv -ppython3.6 >& /dev/null
venv/bin/pip install pre-commit seed-isort-config >& /dev/null
venv/bin/seed-isort-config
grep known_third_party .isort.cfg
pre-commit run seed-isort-config
grep known_third_party .isort.cfg
```

```
$ bash -ex test.sh 
+ rm -rf venv
+ virtualenv venv -ppython3.6
+ venv/bin/pip install pre-commit seed-isort-config
+ venv/bin/seed-isort-config
+ grep known_third_party .isort.cfg
known_third_party=cx_Freeze,py2exe,setuptools,werkzeug
+ pre-commit run seed-isort-config
seed isort known_third_party.............................................Passed
+ grep known_third_party .isort.cfg
known_third_party=cx_Freeze,py2exe,setuptools,werkzeug
```

But, if I do this:

```diff
--- test.sh.old	2018-06-20 13:47:04.000000000 -0700
+++ test.sh	2018-06-20 13:48:07.000000000 -0700
@@ -1,7 +1,9 @@
 rm -rf venv
 virtualenv venv -ppython3.6 >& /dev/null
 venv/bin/pip install pre-commit seed-isort-config >& /dev/null
+venv/bin/pip install versioneer >& /dev/null
 venv/bin/seed-isort-config
 grep known_third_party .isort.cfg
+git checkout -- .
 pre-commit run seed-isort-config
 grep known_third_party .isort.cfg
```

Now it reproduces:

```
$ bash -ex test.sh 
+ rm -rf venv
+ virtualenv venv -ppython3.6
+ venv/bin/pip install pre-commit seed-isort-config
+ venv/bin/pip install versioneer
+ venv/bin/seed-isort-config
+ grep known_third_party .isort.cfg
known_third_party=cx_Freeze,py2exe,setuptools,versioneer,werkzeug
+ git checkout -- .
+ pre-commit run seed-isort-config
seed isort known_third_party.............................................Passed
+ grep known_third_party .isort.cfg
known_third_party=cx_Freeze,py2exe,setuptools,werkzeug
```

The root cause being:

```
# with `versioneer` installed
(Pdb) classify_import('versioneer')
'THIRD_PARTY'
# with `versioneer` not installed
(Pdb) classify_import('versioneer')
'APPLICATION'
```

The root cause is the `versioneer.py` file at the root of the repository shadowing the `versioneer` module installed

**Comment by wakemaster39** [comment]
that would do it, I don't need versioneer installed once it has dropped its payload so I can remove it from the requirements. Thanks for the help sorting that one out, I know how to tackle debugging issues like that in the future now.

**Comment by asottile** [comment]
sweet, thanks for the issue :)
