### ISSUE TITLE
Prevent library from being added by hook (google-cloud-bigquery)

### ISSUE THREAD

**Issue by ykliu0213** [asottile/seed-isort-config#71]
Thanks for the package, I'm finding it really useful.

I'm currently using seed-isort-config as a pre-commit hook. It prevents library, `google-cloud-bigquery`, which defines the `google` namespace. Because of this, It will modify the [setting]known_third_party  from `google-cloud-bigquery` to `google`.

Is there any way to keep `google-cloud-bigquery` in [setting]known_third_party ?
Regards,

**Comment by asottile** [comment]
why would you keep that there? it isn't doing anything

**Comment by ykliu0213** [comment]
Yes, as you say, it doesn't make effect to the service. I'm just curious about this situation. Thanks for replying!
