### ISSUE TITLE
compatible with isort 5.0+

### ISSUE THREAD

**Issue by OneDirection9** [asottile/seed-isort-config#72]
Hi,

For isort 5.0+, there is a new option [extra_standard_library](https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/#known_standard_library). Currently the `seed-isort-config` only filtered out modules at field starts with `known`.

Do we have a plan to support isort 5.0.0?

**Comment by asottile** [comment]
do you mean `known_standard_library` which starts with `known`?

**Comment by asottile** [comment]
and no, this tool I believe is unnecessary in 5.0

**Comment by OneDirection9** [comment]
Got it. Thanks!
